version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Install phase"
      - npm install

  build:
    commands:
      - echo "Build phase"
      - npm run build

  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  files:
    - '**/*'
    - "Procfile"
    - "server.js"
    - "node_modules/**/*"
  base-directory: .
  discard-paths: no